class Locator():

#Login_Page
    click_Sign              = '//*[@id="header"]/div[2]/div/div/nav/div[1]/a'
    Email_addrees           = '//*[@id="email_create"]'
    Create_an_account       = '//*[@id="SubmitCreate"]/span'
    Mesenger01              = '//div[@id="create_account_error"]//li'

# Đăng kí account
    Title                    = '//*[@id="id_gender1"]'
    First_name               =  '//*[@id="customer_firstname"]'
    Last_name                =  '//*[@id="customer_lastname"]'
    Email                    =  '//*[@id="email"]'
    Password                 =  '//*[@id="passwd"]'
    Days                     =  '//*[@id="days"]'
    Click_days               = '//*[@id="days"]/option[5]'
    Months                   =  '//*[@id="months"]'
    Click_Months             = '//*[@id="months"]/option[3]'
    Year                     = '//*[@id="years"]'
    Click_year               = '//*[@id="years"]/option[25]'
    compaly                  = '//*[@id="company"]'
    adrres                   = '//*[@id="address1"]'
    adrres02                 = '//*[@id="address2"]'
    City                     = '//*[@id="city"]'
    State                    = '//*[@id="id_state"]'
    State01                  = '//*[@id="id_state"]/option[3]'
    zipcode                  = '//*[@id="postcode"]'
    Additional               = '//*[@id="other"]'
    Home_phone               = '//*[@id="phone"]'
    Mobile_phone             = '//*[@id="phone_mobile"]'
    Register                 = '//*[@id="submitAccount"]/span'
    My_account               = '//*[@id="columns"]/div[1]/span[2]'

#Homepage
    Newsletter               = '//*[@id="newsletter-input"]'
    Enter_email              = '//*[@id="newsletter_block_left"]/div/form/div/button'
    contact                  = '//*[@id="contact-link"]/a'
    newlet                   = '//*[@id="columns"]/p'
    #test04

    Subjec_Heading           = '//*[@id="id_contact"]'
    Subjec_Heading01         ='//*[@id="id_contact"]/option[2]'
    Home_email_add           = '//*[@id="email"]'
    Order_reference          = '//*[@id="id_order"]'
    Attach                   = '//*[@id="fileUpload"]'
    Send                     = '//*[@id="submitMessage"]'
    Mensenger                = '//*[@id="message"]'
    th                       = '//*[@id="center_column"]/p'


#Locator tìm kiếm
    Search                    = '//*[@id="search_query_top"]'
    text_ser                  = '//div[@class="ac_results"]/ul/li'
    But_ton_sea               = '/html/body/div/div[1]/header/div[3]/div/div/div[2]/form/button'
    li_sp                     = '//ul[@class="product_list grid row"]//a[@class="product-name"]'
    so_sp                     = '//h1//span[2][@class="heading-counter"]'
    gia_sp                    = '//div[@class = "product-image-container"]//*[@class = "price product-price"]'
    Mensenger_sear            = '//div[@class = "center_column col-xs-12 col-sm-9"]/p'

#Locatoe mua hàng
    Click_sp                  = '//*[@id="homefeatured"]/li[1]'
    Add_to_card               = '//p[@class = "buttons_bottom_block no-print"]/button'
    Continue_shopping         = '//div//span[@class = "continue btn btn-default button exclusive-medium"]'
    text_sl_sp                = '//input[@class="text"]'
    Button_check_out          = '//a[@class = "btn btn-default button button-medium"]'
    Button_check_out_summary  = '//p//a[@title = "Proceed to checkout"]'
    id_email                  = '//*[@id="email"]'
    pass_word                 = '//*[@id="passwd"]'
    By_sign                   = '//*[@id="SubmitLogin"]'
    Button_address_checkout   ='//*[@id="center_column"]/form/p/button'
    Button_i_agree            = '//div[@class = "checker hover"]'
    Button_shiping_checkout   = '//*[@id="form"]/p/button'
    Mesenger_by               = '//div[@class = "fancybox-wrap fancybox-desktop fancybox-type-html fancybox-opened"]'
    #thêm vào rỏ hàng
    Add_to_card_01            = '//*[@id="homefeatured"]/li[1]/div/div[2]/div[2]/a[1]'
    Continue_01               ='//*[@id="layer_cart"]/div[1]/div[2]/div[4]/span'
    Add_to_card_02            = '//ul[@class = "product_list grid row homefeatured tab-pane active"]//a[@class= "button ajax_add_to_cart_button btn btn-default"]'
    Continue_02               = '//span[@class = "continue btn btn-default button exclusive-medium"]'
    Button_cart               = '//*[@id="header"]/div[3]/div/div/div[3]/div/a'
    input_sl                  ='//td//input[@class = "cart_quantity_input form-control grey"]'
    Button_clear_sp           = '//td[@class = "cart_delete text-center"]'
    Button_check_out_by       = '//*[@id="center_column"]/p[2]/a[1]'
    Button_4                  = '//*[@id="uniform-cgv"]'
    Button_check_out_shipping = '//button[@class = "button btn btn-default standard-checkout button-medium"]'
    Get_text_sp               = '//td[@class ="cart_total"]//span[@class = "price"]'
    Get_text_sum_sp           ='//*[@id="total_product"]'
    # get_20                   = ' //div[@class = "content_price"]//span[@class = "price-percent-reduction"]'

    Click_img                 = '//ul[@class = "product_list grid row homefeatured tab-pane active"]//img[@class= "replace-2x img-responsive"]'
    Img2                      = '//img[@id = "bigpic"]'
    img_im                    = '//*[@id="product"]/div[2]/div/div[1]'
    Img_003                   = '//*[@id="bigpic"]'
    Text_img_1                = '//div[@class = "fancybox-title fancybox-title-float-wrap"]'
    text_img_2                = '/html/body/div/div[2]/div/div[3]/div/div/div/div[3]/h1'
    Quantity: str             = '//input[@class = "text"]'
    But_toncheckkk            = '//a[@class = "btn btn-default button button-medium"]'
    Null_quantity             = '//p[@class = "fancybox-error"]'
    click_pay_py              = '//a[@class = "cheque"]'
    But_ton_confirn           = '//button[@class = "button btn btn-default button-medium"]'
    check_merseger            = '//p[@class = "alert alert-success"]'
    cloed_mull                = '//a[@class = "fancybox-item fancybox-close"]'
    But_ton_add_to            = '//button[@class = "exclusive"]'
    Button_twitter            = '//button[@class = "btn btn-default btn-twitter"]'
    Cm_sign                   = '//div[@class = "header_user_info"]'
    Button_go_home            = '//ul[@class = "footer_links clearfix"]//a[@class = "btn btn-default button button-small"]'
    But_ton_cmt               = '//a[@id = "new_comment_tab_btn"]'
    Cmt_title                 = '//input[@id = "comment_title"]'
    Cmt_cmt                   = '//textarea[@id = "content"]'
    Button_send               = '//button[@id = "submitNewMessage"]'
    Mer_rv                    = '//div[@class="fancybox-inner"]'
    Send_to_fr                = '//*[@id="send_friend_button"]'
    input_name                = '//input[@id = "friend_name"]'
    input_email               = '//input[@id = "friend_email"]'
    Button_send_email         = '//button[@id = "sendEmail"]'
    mer_sento_fr              = '//div[@class = "fancybox-inner"]'
    input_id_tw               = '//input[@name = "session[username_or_email]"]'
    input_password            = '//input[@name = "session[password]"]'
    click_buton_tw            = '//*[@id="layers"]/div[2]/div/div/div/div/div/div[2]/div[2]/div/div[2]/div[1]'